export const GET_PRODUCTS = 'GET PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET PRODUCTS SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET PRODUCTS ERROR';
export const GET_CATEGORY_PRODUCTS = 'GET CATEGORY PRODUCTS';
export const SHOW_LOADER = 'SHOW LOADER';
export const HIDE_LOADER = 'HIDE LOADER';
export const GET_PRODUCTS_COUNT = 'GET PRODUCTS COUNT';
export const GET_PRODUCTS_COUNT_SUCCESS = 'GET PRODUCTS COUNT SUCCESS';
export const GET_PRODUCTS_COUNT_ERROR = 'GET PRODUCTS COUNT ERROR';

export const ADD_PRODUCT_TO_CART = 'ADD PRODUCT TO CART';
export const REPLACE_CART = 'REPLACE CART';
export const SORT_PRODUCT = 'SORT PRODUCT';
export const GET_CARTS_SUCCESS = 'GET CARTS';